
CREATE TABLE IF NOT EXISTS room (
    id INT(10) UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    type VARCHAR(32) NOT NULL,
    description VARCHAR(256),
    image VARCHAR(256),
    quantity INT(10) UNSIGNED DEFAULT 0,
    price decimal(12,2) UNSIGNED NOT NULL,
    creation BIGINT UNSIGNED NOT NULL,
    lastModified BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customer (
    id INT(10) UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    username VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    creation BIGINT UNSIGNED NOT NULL,
    lastModified BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reservation (
    id INT(10) UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    room_id INT(10) UNSIGNED NOT NULL,
    customer_id INT(10) UNSIGNED NOT NULL,
    quantity INT(10) UNSIGNED NOT NULL,
    start_date BIGINT UNSIGNED NOT NULL,
    end_date BIGINT UNSIGNED NOT NULL,
    cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    creation BIGINT UNSIGNED NOT NULL,
    lastModified BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (room_id) REFERENCES room(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO room VALUES (1, "executive", "executive room only for 1 person", "", 1, 1000, 1521566968000, 1521566968000);
INSERT INTO customer VALUES (1, 'customer', '$2a$10$4yB3di.lJb3/Uh6edRwAlOHU/h31PrcEssd79oS0sNmIHDmUAw9Wu', 'Customer', 1521566968000, 1521566968000);
INSERT INTO reservation VALUES (1, 1, 1, 5, 1553102665000, 1555781065000, FALSE, 1521566968000, 1521566968000);